version: '3'
services:
  centralerros-api:
    image: aceleradev/central-erros-api
    network_mode: bridge
    container_name: central-erros-api
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - central-erros-db
    links:
      - central-erros-db
  central-erros-db:
    image: postgres:10.4
    network_mode: bridge
    container_name: central-erros-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
volumes:
  postgres-data: